version: "3"

services:
  blurred_client:
    container_name: blurred_client
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client/build
    command: yarn start
